### PR TITLE
Reorganize repo

### PR DESCRIPTION
**Pull request by lee-t**
First pass at reorganizing repo for readability. Some questions remain:

- does this make sense? should we keep gpt-4 and llama in different directories?
- should there be more documentation on infrastructure? like a markdown version of the datasets (the csv files) and/or more detailed notebooks?
-  something else?

### CODE REVIEW

**Review by andrewGhazi — APPROVED** [review]
I'd leave the "2" in any time there's a filename relevant to llama2 (i.e. `llama2_bioc_qa.csv` instead of `llama_bioc_qa.csv`) for the sake of clarity but otherwise yes this reorganization definitely seems like an improvement.

**Comment by lee-t** [comment]
@nturaga based on feedback, its better to divide your notebook for all the Azure code to be seperated by task. One for Q&A(embedding) and one for code-diffusion. Also could you seperate the LLM-as-judge task and put it in its own dir in eval?

**Comment by nturaga** [comment]
Sounds good to me.

**Review by nturaga — APPROVED** [review]

**Comment by lee-t** [comment]
merged after tues chatbot meeting

**Pull request merged**
